[project]
name = "SportHub"
version = "0.7.2"
description = "Тестовое задание на Django"

authors = "TFsadReD"
readme = "README.md"
license = "MIT License"
repository = "https://github.com/TFsadReD/SportHub-Django"

requires-python = ">=3.14"
dependencies = [
    "django>=6.0.7",
    "python-dotenv>=1.2.2",
]
