# Generated by Django 6.0.7 on 2026-07-30 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Как к вам обращаться?', max_length=100, verbose_name='Имя автора')),
                ('assessment', models.PositiveSmallIntegerField(choices=[(1, '1 ★ - Ужасно'), (2, '2 ★★ - Плохо'), (3, '3 ★★★ - Удовлетворительно'), (4, '4 ★★★★ - Хорошо'), (5, '5 ★★★★★ - Идеально')], help_text='Оценка от 1 до 5 звёзд', validators=[django.core.validators.MinValueValidator(1, message='Минимальная оценка - 1'), django.core.validators.MaxValueValidator(5, message='Максимальная оценка - 5')], verbose_name='Оценка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(help_text='Опишите ваши впечатления от посещения клуба', verbose_name='Текст отзыва')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Отображать ли отзыв на сайте', verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
