# Generated by Django 6.0.7 on 2026-07-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Опишите ваши впечатления от посещения клуба', max_length=250, verbose_name='Текст отзыва'),
        ),
    ]
